name: Build Android APK

on:
  push:
    paths:
      - "*.zip"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project
        run: |
          unzip "*.zip" -d temp

          cp -r temp/*/* .
          rm -rf temp
          rm *.zip

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Give execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: xinsu-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Commit extracted project
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .
          git commit -m "Auto extract project" || exit 0
          git push
