name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Verify project structure
        run: |
          echo "===== ROOT ====="
          ls -la

          echo "===== WRAPPER ====="
          ls -la gradle/wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: xinsu-debug-apk
          path: app/build/outputs/apk/debug/*.apk
